name: s-g-mle-pl
channels:
  - conda-forge
dependencies:
  - python=3.10.14
  - numpy
  - osgeo
  - scipy
  - warnings
  - sys
  - os
  - multiprocessing
  - matplotlib
  - functools
  - tqdm
  - argsparse
  - pip
  - ipython
  - pip:
    - pyyaml